const shopItemsData = [
    {
      id: "thyfhcb23",
      name: "Casual Shirt",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.lorem20 means by itself even",
      img: "https://images.pexels.com/photos/899357/pexels-photo-899357.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb24",
      name: "Office Shirt",
      price: 100,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb25",
      name: "T Shirt",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/2356344/pexels-photo-2356344.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb26",
      name: "Mens Suit",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/4894829/pexels-photo-4894829.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb27",
      name: "Womens Jewellery",
      price: 3900,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/15181110/pexels-photo-15181110/free-photo-of-woman-in-traditional-bridal-saree-dress.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb28",
      name: "Womens Saree",
      price: 6000,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/10637779/pexels-photo-10637779.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb29",
      name: "Bag",
      price: 600,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb30",
      name: "Backpack",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb31",
      name: "Womens Ring",
      price: 20000,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/1232931/pexels-photo-1232931.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb32",
      name: "Womens Earrings",
      price: 4000,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/3266700/pexels-photo-3266700.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb33",
      name: "Smart Watches",
      price: 2000,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: "thyfhcb34",
      name: "Earpods",
      price: 6000,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://images.pexels.com/photos/16703772/pexels-photo-16703772/free-photo-of-close-up-of-wireless-earphones-and-case.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    },
  ];